services:
  besu-node:
    image: hyperledger/besu:latest
    container_name: besu-node
    ports:
      - "8546:8546"      # WebSocket JSON-RPC
      - "8550:8550"      # HTTP JSON-RPC
      - "30310:30310/tcp"  # P2P TCP
      - "30310:30310/udp"  # P2P UDP
      - "30303:30303"      # Bootnode port
    volumes:
      - ./DVRE-Node/data:/opt/besu/data
      - ./DVRE-Node/genesis.json:/opt/besu/genesis.json
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://82cab8884f3e7cce8d3ed578e7e64e6e25e4252027c796d91e3d0bd2eb604c60a7116e9e2d7c8dd2e48ca41c1109456569bc2f40cba8bdbc3afa503593ea0b2c@145.100.135.27:30310
      --p2p-port=30310
      --rpc-http-port=8550
      --p2p-host=145.100.135.97
      --rpc-http-host=0.0.0.0
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,IBFT
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --rpc-ws-api=ETH,NET,WEB3
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --min-gas-price=0
